### PR TITLE
Bump requirements to include tap.py 3.0

### PR DESCRIPTION
**Pull request by ecederstrand**
To accept your contribution, please complete the checklist below.

* [x] Is your name/identity in the AUTHORS file alphabetically?
* [ ] Did you write a test to verify your code change?
* [x] Is CI passing?

### CODE REVIEW

**Comment by ecederstrand** [comment]
tap.py 3.0 does not support Python 2.7, so py27 and pypy tests are failing.

Python 2.7 is deprecated as of January 1, 2020. Is it time to remove support for Python 2.7 in this package?

**Comment by mblayman** [comment]
Yep, you're right. I think we can remove the py27 section in Travis and replace pypy with pypy3 (see https://github.com/python-tap/tappy/blob/master/.travis.yml for an example).

**Comment by mblayman** [comment]
Can you also add your name alphabetically to the AUTHORS file of this repo? I know your name is in the tappy AUTHORS file, but pytest-tap is a separate project so it has a separate AUTHORS file.

**Comment by ecederstrand** [comment]
Sure. I got the two projects mixed up, so I thought I was already in the AUTHORS :-)

**Comment by ecederstrand** [comment]
Wow, I can't even operate the alphabet anymore. Thanks :-)

**Pull request merged**
